<?php

namespace App\Filament\Resources;

use App\Filament\Resources\BinotelIntegrationResource\Pages\ListBinotelAccounts;
use App\Filament\Resources\BinotelIntegrationResource\Pages\ViewBinotelAccount;
use App\Models\BinotelAccount;
use BackedEnum;
use Filament\Actions\EditAction;
use Filament\Actions\ViewAction;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

/**
 * Binotel API gateway connection.
 *
 * Mirrors the existing integration pattern: List + View routes, Create/Edit
 * as modals, navigation group "Інтеграції", and default-deny permissions
 * generated by Filament Shield.
 */
class BinotelIntegrationResource extends Resource
{
    protected static ?string $model = BinotelAccount::class;

    protected static string|BackedEnum|null $navigationIcon = 'heroicon-o-phone';

    protected static ?string $navigationLabel = 'Binotel';

    protected static string|\UnitEnum|null $navigationGroup = 'Інтеграції';

    protected static ?int $navigationSort = 12;

    protected static ?string $modelLabel = 'підключення Binotel';

    protected static ?string $pluralModelLabel = 'підключення Binotel';

    public static function form(Schema $schema): Schema
    {
        return $schema->components([
            TextInput::make('display_name')
                ->label('Назва')
                ->placeholder('Binotel — основний акаунт')
                ->required()
                ->maxLength(255),

            TextInput::make('company_name')
                ->label('Компанія')
                ->placeholder('Балкони Вікна Київ')
                ->maxLength(255),

            TextInput::make('company_id')
                ->label('Company ID')
                ->placeholder('123456')
                ->required()
                ->maxLength(255)
                ->helperText('Ідентифікатор компанії Binotel, який надає підтримка разом з API Key і API Secret.'),

            TextInput::make('api_key')
                ->label('API Key')
                ->required()
                ->maxLength(255),

            TextInput::make('api_secret')
                ->label('API Secret')
                ->password()
                ->revealable()
                ->required()
                ->maxLength(500)
                ->helperText('Зберігається в зашифрованому вигляді.'),

            Toggle::make('is_active')
                ->label('Активний')
                ->default(true)
                ->inline(false),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('display_name')
                    ->label('Назва')
                    ->searchable()
                    ->sortable(),

                TextColumn::make('company_name')
                    ->label('Компанія')
                    ->placeholder('—')
                    ->searchable()
                    ->toggleable(),

                TextColumn::make('company_id')
                    ->label('Company ID')
                    ->searchable()
                    ->toggleable(),

                TextColumn::make('api_key')
                    ->label('API Key')
                    ->formatStateUsing(fn (string $state): string => substr($state, 0, 4).' ... '.substr($state, -4))
                    ->tooltip(fn (BinotelAccount $record): string => $record->api_key),

                IconColumn::make('is_active')
                    ->label('Активний')
                    ->boolean(),

                TextColumn::make('updated_at')
                    ->label('Оновлено')
                    ->since()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->recordUrl(fn (BinotelAccount $record): string => static::getUrl('view', ['record' => $record]))
            ->recordActions([
                ViewAction::make(),
                EditAction::make()
                    ->visible(fn (): bool => auth()->user()?->getActiveRoleName() !== 'Керівник компанії'),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => ListBinotelAccounts::route('/'),
            'view' => ViewBinotelAccount::route('/{record}'),
        ];
    }
}
